var test = require('tape')
var dtype = require('./')

test('dtype', function(t) {
  var arr = dtype('int8')
  t.equal(arr, Int8Array)
  arr = dtype('int16')
  t.equal(arr, Int16Array)
  arr = dtype('int32')
  t.equal(arr, Int32Array)
  arr = dtype('uint8')
  t.equal(arr, Uint8Array)
  arr = dtype('uint16')
  t.equal(arr, Uint16Array)
  arr = dtype('uint32')
  t.equal(arr, Uint32Array)
  arr = dtype('float32')
  t.equal(arr, Float32Array)
  arr = dtype('float64')
  t.equal(arr, Float64Array)
  arr = dtype('array')
  t.equal(arr, Array)
  arr = dtype('uint8_clamped')
  t.equal(arr, Uint8ClampedArray)
  t.equal(dtype('buffer'), Buffer)
  t.equal(dtype('generic'), ArrayBuffer)
  t.equal(dtype('data'), ArrayBuffer)
  t.equal(dtype('dataview'), ArrayBuffer)
  t.end()
})
